version: '3'

services:

  proxy:
    build:
      context: ./proxy
    image: damianpeaf/so1-proyecto1-proxy
    ports:
      - "80:80"
    restart: always
    depends_on:
      - frontend
      - backend

  frontend:
    build:
      context: ./frontend
    image: damianpeaf/so1-proyecto1-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    image: damianpeaf/so1-proyecto1-backend
    restart: always
    privileged: true
    volumes:
      - /proc:/proc
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    build:
      context: ./db
    image: damianpeaf/so1-proyecto1-db
    ports:
      - "3306:3306"
    volumes:
      - so1-db-vol:/var/lib/mysql

volumes:
  so1-db-vol:
