apiVersion: 1

datasources:
  - name: Redis
    type: redis-datasource
    access: proxy
    isDefault: true
    orgId: 1
    url: redis://redis-svc:6379
    uid: R3d1sD4t4S0urc3
    jsonData:
      poolSize: 5
      timeout: 10
      pingInterval: 0
      pipelineWindow: 0
    editable: true
    secureJsonData:
      password: R3d1sP4ssw0rd

    apiVersion: 1
