apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-consumers
  namespace: so1-proyecto2
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: golang-consumer
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 35
