version: '3'

services:

  grpc-client:
    build:
      context: ./grpc-client
    image: damianpeaf/so1-proyecto2-grpc-client
    restart: always
    ports:
      - "8080:8080"
      
  grpc-server:
    build:
      context: ./grpc-server
    image: damianpeaf/so1-proyecto2-grpc-server
    restart: always
    ports:
      - "3001:3001"

  consumer:
    build:
      context: ./consumer
    image: damianpeaf/so1-proyecto2-consumer
    restart: always

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  grafana:
    build:
      context: ./grafana
    image: damianpeaf/so1-proyecto2-grafana
    restart: always
    ports:
      - "3000:3000"

  rust-client:
    build:
      context: ./rust-client
    image: damianpeaf/so1-proyecto2-rust-client
    restart: always
    ports:
      - "3000:3000"

  rust-server:
    build:
      context: ./rust-server
    image: damianpeaf/so1-proyecto2-rust-server
    restart: always
    ports:
      - "3001:3001"